### ISSUE TITLE
Make RE_REF_TAG configurable in _config.yml

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/jekyll-sheafy#4]
I had the feeling this would be necessary, and in fact it took just a couple of days to be needed by @jonsterling :laughing: -- see https://github.com/jonsterling/jekyll-sheafy/commit/8d71f5d2656abf01fc2281d362ced7d2c63fac7d#diff-cef05919610621f5fe9f9413512331b7512c762501a4bec0166feeb73da820e6R4

It should be possible to configure a list of reference matchers in the configuration to allow for arbitrary syntax:

```yaml
sheafy:
  references:
    matchers:
      - !ruby/regexp /{%\s*[cp]?ref (?<slug>.+?)\s*%}/
      - !ruby/regexp /@cite{(?<slug>.+?)}/
```

We should ensure there's a matching group named `slug`, of course.
